executable              = train_JetClass.sh
arguments               = $(ClusterId)$(ProcId)
output                  = train_JetClass.$(ClusterId).$(ProcId).out
error                   = train_JetClass.$(ClusterId).$(ProcId).err
log                     = train_JetClass.$(ClusterId).log
should_transfer_files   = YES
transfer_input_files    = matrix.py 
when_to_transfer_output = ON_EXIT
request_GPUs = 2
request_CPUs = 1
queue